apiVersion: batch/v1
kind: CronJob
metadata:
  name: dice
spec:
  jobTemplate:
    metadata:
      name: dic
    spec:
      completions: 1
      backoffLimit: 25
      activeDeadlineSeconds: 20
      template:
        metadata: {}
        spec:
          containers:
          - image: kodekloud/throw-dice
            name: throw-dice
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
